"""Compose-backend plumbing for the AIHR turnkey database.

The docker-only half of :mod:`hr.db_admin` (split for the 250-LOC module
ceiling): runner seam, compose argv, env-file persistence, container probes,
readiness polling. Pure functions with an injectable subprocess ``Runner``
(argv lists only, never a shell) so every branch is testable hermetically
without docker or a live database. ``hr.db_admin`` re-exports everything here
and owns the backend decision tree (compose vs embedded).
"""

from __future__ import annotations

import errno
import os
import re
import secrets
import socket
import subprocess
import time
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from hr import config
from hr.config_resources import DB_DEFAULT_PORT, db_env_file, read_db_env_file

COMPOSE_PROJECT = "aihr"
COMPOSE_SERVICE = "aihr-db"
CONTAINER = "aihr-db"
READY_TIMEOUT_S = 60.0
READY_POLL_INTERVAL_S = 2.0
_UP_TIMEOUT_S = 300
_DOCKER_TIMEOUT_S = 15
_MASKED = "***"
_CONFIG_FILES_TEMPLATE = '{{index .Config.Labels "com.docker.compose.project.config_files"}}'
_NO_VALUE = "<no value>"


@dataclass(frozen=True)
class CommandResult:
    rc: int
    stdout: str
    stderr: str


Runner = Callable[[list[str], int], CommandResult]


def default_runner(argv: list[str], timeout: int) -> CommandResult:
    proc = subprocess.run(  # noqa: S603 — argv list, no shell, argv fully controlled above
        argv,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    return CommandResult(proc.returncode, proc.stdout, proc.stderr)


def docker_compose_dir() -> Path:
    return config.hr_home() / "docker"


def compose_file_path() -> Path:
    return docker_compose_dir() / "docker-compose.yml"


def generate_db_password() -> str:
    return secrets.token_urlsafe(32)


def render_db_env(password: str, port: int) -> str:
    return (
        "# AIHR database credentials — generated by `hr db-up` (keep mode 0600).\n"
        f"AIHR_DB_PASSWORD={password}\n"
        f"AIHR_DB_PORT={port}\n"
    )


def write_db_env_file(path: Path, password: str, port: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_db_env(password, port), encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass  # best-effort: POSIX mode unsupported (Windows) must not fail db-up


def ensure_db_env_file(port: int | None) -> tuple[Path, int, bool]:
    """Resolve the db env file, generating it when missing; (path, port, wrote).

    An explicit ``port`` (from ``--port``) rewrites only the port line of an
    existing file — the persisted password is never regenerated on restart.
    """
    path = db_env_file(for_write=True)
    if path is None:  # pragma: no cover — write mode always resolves a path
        raise RuntimeError("no writable db env file location (docker/ and data dir both unwritable)")
    values = read_db_env_file(path)
    password = values.get("AIHR_DB_PASSWORD", "")
    file_port_raw = values.get("AIHR_DB_PORT", "")
    file_port = int(file_port_raw) if file_port_raw.isdigit() else None
    effective = port if port is not None else (file_port or DB_DEFAULT_PORT)
    if password and (port is None or port == file_port):
        return path, effective, False
    write_db_env_file(path, password or generate_db_password(), effective)
    return path, effective, True


def compose_argv(env_file: Path | None, args: Sequence[str]) -> list[str]:
    """docker compose argv pinned to the AIHR project, env file explicit.

    ``--env-file`` is always passed when the db env file is known so the
    fallback data-dir location works identically to ``docker/.env``.
    """
    argv = [
        "docker", "compose",
        "-p", COMPOSE_PROJECT,
        "--project-directory", str(docker_compose_dir()),
    ]
    if env_file is not None:
        argv += ["--env-file", str(env_file)]
    return [*argv, *args]


def is_port_bound(port: int, host: str = "127.0.0.1") -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        try:
            probe.bind((host, port))
        except OSError as exc:
            return exc.errno == errno.EADDRINUSE
        return False


def container_status(run: Runner, name: str = CONTAINER) -> str:
    """``docker inspect`` state string ("" when the container is absent)."""
    res = run(["docker", "inspect", "-f", "{{.State.Status}}", name], _DOCKER_TIMEOUT_S)
    return res.stdout.strip() if res.rc == 0 else ""


def foreign_compose_conflict(run: Runner, name: str = CONTAINER) -> Optional[str]:
    """Refusal message when ``name`` exists but is not managed by our compose file.

    One shared AIHR database per host is the contract: an ``aihr-db`` container
    created by a different install (or by a bare ``docker run``) must never be
    silently recreated by our ``docker compose up``. Returns ``None`` (safe to
    proceed) when the container is absent, or when its compose ``config_files``
    label includes this install's compose manifest — that is the idempotent
    same-install re-up.
    """
    state = container_status(run, name)
    if not state:
        return None
    res = run(["docker", "inspect", "-f", _CONFIG_FILES_TEMPLATE, name], _DOCKER_TIMEOUT_S)
    entries = (
        [e.strip() for e in res.stdout.split(",") if e.strip() and e.strip() != _NO_VALUE]
        if res.rc == 0
        else []
    )
    paths = [e for e in entries if "/" in e or "\\" in e]
    ours = compose_file_path().resolve()
    if any(Path(p).resolve() == ours for p in paths) or (entries and not paths):
        return None
    if paths:
        return (
            f"error: container {name} is managed by a different compose file than ours — "
            f"refusing to take it over (foreign: {', '.join(paths)}; ours: {ours}). "
            "One shared AIHR database per host is the contract: manage it via one install, "
            "or run `hr db-down` from the owning install first. "
            f"Re-run with --force only if {name} should belong to THIS install."
        )
    return (
        f"error: a container named {name} is already {state} but no AIHR compose project "
        "manages it (compose label missing or unreadable) — refusing to recreate a "
        "foreign container. One shared AIHR database per host is the contract: remove "
        f"the foreign {name} container first, or re-run with --force to take it over."
    )


def wait_for_ready(
    run: Runner,
    *,
    timeout_s: float | None = None,
    interval_s: float | None = None,
    sleep: Callable[[float], None] = time.sleep,
) -> bool:
    """Poll ``pg_isready`` inside the container until it accepts connections."""
    interval = READY_POLL_INTERVAL_S if interval_s is None else interval_s
    timeout = READY_TIMEOUT_S if timeout_s is None else timeout_s
    attempts = max(1, int(timeout / interval))
    for _attempt in range(attempts):
        res = run(
            ["docker", "exec", CONTAINER, "pg_isready", "-U", "aihr", "-d", "aihr"],
            _DOCKER_TIMEOUT_S,
        )
        if res.rc == 0:
            return True
        sleep(interval)
    return False


def mask_dsn(dsn: str) -> str:
    """Replace the password component of a postgres DSN with ``***``."""
    return re.sub(r"://([^:@/]+):[^@]+@", rf"://\1:{_MASKED}@", dsn)


def _tail(text: str, limit: int = 3) -> str:
    lines = [ln for ln in text.strip().splitlines() if ln.strip()]
    return " | ".join(lines[-limit:]) if lines else "(no output)"
