"""Build a self-contained AIHR turnkey bundle (Item 11 packaging).

Run from the repo root::

    uv run --with pyinstaller python scripts/build_bundle.py \\
        --os linux --arch x86_64 --version 0.4.0 --out dist/

Produces ``dist/aihr-<version>-<os>-<arch>.tar.gz`` (or ``.zip`` on windows)
plus a ``.sha256`` sidecar. Staging layout (no top-level prefix in the
archive) and pinning rules: see ``scripts/bundle_core.py``.

Network is used for exactly one thing: downloading the pinned theseus-rs
PostgreSQL asset (cached under --pg-cache, sha256-verified before reuse).
``--self-test`` runs the pure logic offline; ``--list`` / ``--verify``
inspect a produced archive.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
import zipfile
from importlib.util import find_spec
from pathlib import Path
from typing import Final

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.bundle_core import (  # noqa: E402  (sys.path bootstrap precedes the import)
    ARCH_NAMES,
    OS_NAMES,
    PG_LIBS_NOTICE,
    BundleError,
    DebPin,
    PgPin,
    PgTarget,
    archive_kind_for,
    bundle_archive_name,
    check_bundle_members,
    default_pg_cache_dir,
    default_repo_root,
    download_url,
    exe_suffix,
    libs_pin_file,
    load_pin_text,
    normalize_pg,
    parse_libs_pin,
    pick_pg_root,
    pick_target,
    pin_file,
    required_bundle_members,
    sha256_file,
    sidecar_text,
    verify_archive_checksum,
)

#: Modules that PyInstaller's static graph may miss behind optional/lazy imports.
HIDDEN_IMPORTS: Final[tuple[str, ...]] = (
    "psycopg2",
    "psycopg2.extensions",
    "typer",
    "rich",
    "yaml",
)

_ENTRY_STUB = '''"""Frozen console entry point for the AIHR bundle (generated by build_bundle.py)."""

from hr.cli import app

if __name__ == "__main__":
    app()
'''


def _log(msg: str) -> None:
    print(f"[bundle] {msg}", flush=True)


# --------------------------------------------------------------------------
# (b) vendored PostgreSQL
# --------------------------------------------------------------------------


def fetch_pg(pin: PgPin, target: PgTarget, cache_dir: Path) -> Path:
    """Return the cached theseus asset path, downloading + sha256-verifying on miss.

    A cached file with the wrong digest is treated as a poisoned cache entry:
    it is re-downloaded once, and a second mismatch is a hard error.
    """
    cache_dir.mkdir(parents=True, exist_ok=True)
    dest = cache_dir / target.asset
    for attempt in (1, 2):
        if dest.is_file():
            actual = sha256_file(dest)
            if actual == target.sha256:
                _log(f"pg cache hit (sha256 verified): {dest.name}")
                return dest
            if attempt == 1:
                _log(f"WARNING: cache digest mismatch for {dest.name}; re-downloading")
                dest.unlink()
            else:
                raise BundleError(
                    f"re-downloaded asset still has wrong sha256 for {target.asset}: "
                    f"{actual} != {target.sha256}"
                )
        url = download_url(pin, target)
        _log(f"downloading {url}")
        request = urllib.request.Request(url, headers={"User-Agent": "aihr-build-bundle"})
        tmp = dest.with_name(f"{target.asset}.part{attempt}")
        with urllib.request.urlopen(request, timeout=300) as resp, tmp.open("wb") as fh:
            shutil.copyfileobj(resp, fh)
        actual = sha256_file(tmp)
        if actual != target.sha256:
            tmp.unlink(missing_ok=True)
            if attempt == 1:
                continue
            raise BundleError(
                f"downloaded asset has wrong sha256 for {target.asset}: "
                f"{actual} != {target.sha256}"
            )
        tmp.replace(dest)
        _log(f"pg cached: {dest} ({dest.stat().st_size} bytes)")
        return dest
    raise BundleError(f"unreachable: fetch loop for {target.asset} exited without result")


def extract_pg(archive: Path, kind: str, dest: Path) -> Path:
    """Extract a theseus tar.gz/zip into ``dest`` and return the normalized pg root."""
    dest.mkdir(parents=True, exist_ok=True)
    if kind == "tar.gz":
        with tarfile.open(archive, "r:gz") as tf:
            tf.extractall(dest, filter="data")
    else:
        with zipfile.ZipFile(archive) as zf:
            zf.extractall(dest)
    return pick_pg_root(dest)


# --------------------------------------------------------------------------
# (a2) linux system-library closure: pinned .deb -> pg/lib/
# --------------------------------------------------------------------------


def fetch_deb(entry: DebPin, cache_dir: Path) -> Path:
    """Return the cached .deb, downloading + sha256-verifying on miss.

    Same poisoned-cache contract as :func:`fetch_pg`: re-download once, hard
    error on a second mismatch.
    """
    cache_dir.mkdir(parents=True, exist_ok=True)
    dest = cache_dir / entry.asset
    for attempt in (1, 2):
        if dest.is_file():
            actual = sha256_file(dest)
            if actual == entry.sha256:
                _log(f"deb cache hit (sha256 verified): {dest.name}")
                return dest
            if attempt == 1:
                _log(f"WARNING: cache digest mismatch for {dest.name}; re-downloading")
                dest.unlink()
            else:
                raise BundleError(
                    f"re-downloaded .deb still has wrong sha256 for {entry.asset}: "
                    f"{actual} != {entry.sha256}"
                )
        _log(f"downloading {entry.url}")
        request = urllib.request.Request(entry.url, headers={"User-Agent": "aihr-build-bundle"})
        tmp = dest.with_name(f"{entry.asset}.part{attempt}")
        with urllib.request.urlopen(request, timeout=300) as resp, tmp.open("wb") as fh:
            shutil.copyfileobj(resp, fh)
        actual = sha256_file(tmp)
        if actual != entry.sha256:
            tmp.unlink(missing_ok=True)
            raise BundleError(f"downloaded .deb sha256 mismatch for {entry.asset}")
        tmp.rename(dest)
        return dest
    raise BundleError("unreachable: fetch loop returned no path")


def stage_pg_libs(repo: Path, pg_dest: Path, cache_dir: Path) -> list[str]:
    """Vendor the pinned library closure into ``pg_dest/lib`` (linux targets).

    Requires GNU ``ar`` + zstd-capable ``tar`` on PATH (both present on the
    CI ubuntu runners). Returns the staged member names for logging.
    """
    entries = parse_libs_pin(libs_pin_file(repo).read_text(encoding="utf-8"))
    lib_dir = pg_dest / "lib"
    lib_dir.mkdir(parents=True, exist_ok=True)
    staged: list[str] = []
    for entry in entries:
        deb = fetch_deb(entry, cache_dir)
        with tempfile.TemporaryDirectory(prefix="aihr-deb-") as tmp:
            work = Path(tmp)
            subprocess.run(["ar", "x", str(deb)], check=True, cwd=work)
            data = next(iter(sorted(work.glob("data.tar.*"))), None)
            if data is None:
                raise BundleError(f"{deb.name} contains no data.tar.* member")
            subprocess.run(["tar", "-xf", str(data.name)], check=True, cwd=work)
            for spec in entry.files:
                src = work / spec.member
                if not src.is_file():
                    raise BundleError(f"{deb.name} lacks member {spec.member}")
                shutil.copy2(src, lib_dir / spec.dest)
                link = lib_dir / spec.symlink
                if link.is_symlink() or link.exists():
                    link.unlink()
                link.symlink_to(spec.dest)
                staged.append(f"pg/lib/{spec.symlink} -> {spec.dest}")
    (lib_dir / "NOTICE").write_text(PG_LIBS_NOTICE, encoding="utf-8")
    staged.append("pg/lib/NOTICE")
    return staged


# --------------------------------------------------------------------------
# (a) PyInstaller onedir build of the console entry `hr`
# --------------------------------------------------------------------------


def run_pyinstaller(repo: Path, work: Path, app_dest: Path) -> Path:
    """Freeze the `hr` CLI into an onedir tree at ``app_dest``; return it.

    The post-archive ``smoke_app`` run is the build gate (frozen ``hr --help``).
    """
    if find_spec("PyInstaller") is None:
        raise BundleError(
            "PyInstaller not importable — run this script via "
            "`uv run --with pyinstaller python scripts/build_bundle.py ...`"
        )
    pyi = work / "pyinstaller"
    entry = pyi / "hr_entry.py"
    entry.parent.mkdir(parents=True, exist_ok=True)
    entry.write_text(_ENTRY_STUB, encoding="utf-8")
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onedir",
        "--console",
        "--name",
        "hr",
        "--paths",
        str(repo),
        "--copy-metadata",
        "aihr",
        *(f"--hidden-import={m}" for m in HIDDEN_IMPORTS),
        "--distpath",
        str(pyi / "dist"),
        "--workpath",
        str(pyi / "build"),
        "--specpath",
        str(pyi),
        str(entry),
    ]
    _log(f"pyinstaller: {' '.join(cmd[:10])} ...")
    subprocess.run(cmd, check=True, cwd=repo)
    built = pyi / "dist" / "hr"
    if not built.is_dir():
        raise BundleError(f"PyInstaller did not produce onedir tree at {built}")
    shutil.copytree(built, app_dest, dirs_exist_ok=True, symlinks=True)
    return app_dest


def smoke_app(app_dir: Path, os_name: str) -> None:
    """Run ``app/hr --help`` from the frozen tree — the build smoke gate."""
    exe = app_dir / f"hr{exe_suffix(os_name)}"
    if not exe.is_file():
        raise BundleError(f"bundle app executable missing: {exe}")
    proc = subprocess.run([str(exe), "--help"], capture_output=True, text=True, timeout=120)
    if proc.returncode != 0:
        raise BundleError(
            f"frozen `hr --help` exited {proc.returncode}\n"
            f"stdout: {proc.stdout[-2000:]}\nstderr: {proc.stderr[-2000:]}"
        )
    _log("smoke ok: frozen `hr --help` exits 0")


def _fabricate_stub_app(app_dir: Path, os_name: str) -> None:
    app_dir.mkdir(parents=True, exist_ok=True)
    internal = app_dir / "_internal"
    internal.mkdir(exist_ok=True)
    (internal / "base_library.zip").write_bytes(b"aihr-stub")
    entry = app_dir / f"hr{exe_suffix(os_name)}"
    entry.write_text("#!/bin/sh\necho 'hr stub: layout-test bundle, not release-grade'\n", encoding="utf-8")
    entry.chmod(0o755)


# --------------------------------------------------------------------------
# share/aihr templates + (c) assembly + archive
# --------------------------------------------------------------------------


def build_share(repo: Path, dest_share: Path) -> None:
    """Copy the repo templates into D-layout share/aihr/ (secret-free by contract)."""
    template = repo / "hr.toml.example"
    configs_dir = repo / "configs"
    if not template.is_file() or not configs_dir.is_dir():
        raise BundleError(f"repo templates missing: {template} / {configs_dir}")
    target = dest_share / "aihr"
    (target / "configs").mkdir(parents=True, exist_ok=True)
    shutil.copy2(template, target / "hr.toml.example")
    shipped = 0
    for yaml_file in sorted(configs_dir.glob("*.yaml")):
        if yaml_file.name.endswith(".local.yaml"):  # gitignored local overlays: never ship
            continue
        shutil.copy2(yaml_file, target / "configs" / yaml_file.name)
        shipped += 1
    _log(f"share templates: hr.toml.example + {shipped} configs/*.yaml")


def create_archive(stage: Path, archive: Path, kind: str) -> None:
    if kind == "tar.gz":
        with tarfile.open(archive, "w:gz", compresslevel=9) as tf:
            for child in sorted(stage.iterdir()):
                tf.add(child, arcname=child.name)  # preserves exec bits from staging
    else:
        with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
            for path in sorted(stage.rglob("*")):
                if path.is_file():
                    zf.write(path, path.relative_to(stage).as_posix())


def write_sidecar(archive: Path) -> Path:
    sidecar = archive.with_name(archive.name + ".sha256")
    sidecar.write_text(sidecar_text(archive.name, sha256_file(archive)), encoding="ascii")
    return sidecar


# --------------------------------------------------------------------------
# --list / --verify
# --------------------------------------------------------------------------


def list_members(archive: Path) -> list[str]:
    if archive.name.endswith(".tar.gz"):
        with tarfile.open(archive, "r:gz") as tf:
            return [m.name for m in tf.getmembers()]
    with zipfile.ZipFile(archive) as zf:
        return zf.namelist()


def os_from_archive_name(name: str) -> str:
    for os_name in OS_NAMES:
        if f"-{os_name}-" in name:
            return os_name
    raise BundleError(f"cannot infer target OS from archive name: {name}")


def handle_verify(archive: Path) -> int:
    os_name = os_from_archive_name(archive.name)
    expected, actual = verify_archive_checksum(archive)
    problems = check_bundle_members(list_members(archive), os_name)
    if problems:
        for p in problems:
            print(f"  LAYOUT PROBLEM: {p}")
        return 1
    print(f"OK {archive.name}\n  sha256 verified: {actual} (sidecar match: {expected})")
    for req in required_bundle_members(os_name):
        print(f"  present: {req}")
    return 0


def handle_list(archive: Path) -> int:
    for member in list_members(archive):
        print(member)
    return 0


# --------------------------------------------------------------------------
# orchestration
# --------------------------------------------------------------------------


def build_bundle(args: argparse.Namespace) -> int:
    repo: Path = args.repo
    out: Path = args.out
    pin = load_pin_text(pin_file(repo).read_text(encoding="utf-8"))
    target = pick_target(pin, args.os, args.arch)
    if target.kind != archive_kind_for(args.os):
        raise BundleError(f"pin target kind {target.kind} inconsistent with os {args.os}")
    _log(f"pg pin: {pin.source_repo} @ {pin.release_tag} -> {', '.join(sorted(pin.targets))}")

    stage = out / ".bundle-stage" / f"{args.os}-{args.arch}"
    work = out / ".bundle-work" / f"{args.os}-{args.arch}"
    if args.skip_pg and not (stage / "pg").is_dir():
        raise BundleError(f"--skip-pg requires an existing staged pg/ tree: {stage / 'pg'}")
    if not (args.skip_pyinstaller or args.skip_pg):
        shutil.rmtree(stage, ignore_errors=True)
    stage.mkdir(parents=True, exist_ok=True)
    work.mkdir(parents=True, exist_ok=True)

    app_stubbed = False
    if args.skip_pyinstaller:
        if (stage / "app").is_dir():
            _log(f"stage app: reusing staged tree {stage / 'app'}")
        else:
            _log("stage app: fabricated layout stub (--skip-pyinstaller, no staged app/)")
            _fabricate_stub_app(stage / "app", args.os)
            app_stubbed = True
    else:
        _log("stage app: PyInstaller onedir `hr`")
        shutil.rmtree(stage / "app", ignore_errors=True)
        run_pyinstaller(repo, work, stage / "app")

    if args.skip_pg:
        if not (stage / "pg").is_dir():
            raise BundleError("--skip-pg but stage/pg does not exist")
    else:
        _log(f"stage pg: theseus {pin.release_tag} ({target.triple})")
        cached = fetch_pg(pin, target, args.pg_cache)
        with tempfile.TemporaryDirectory(prefix="aihr-pg-") as tmp:
            root = extract_pg(cached, target.kind, Path(tmp) / "x")
            shutil.rmtree(stage / "pg", ignore_errors=True)
            normalize_pg(root, stage / "pg", args.os)
        if args.os == "linux":
            for member in stage_pg_libs(repo, stage / "pg", args.pg_cache.parent / "libs"):
                _log(f"  vendored {member}")

    _log("stage share: repo templates -> share/aihr/")
    shutil.rmtree(stage / "share", ignore_errors=True)
    build_share(repo, stage / "share")

    archive = out / bundle_archive_name(args.version, args.os, args.arch)
    _log(f"archiving -> {archive}")
    create_archive(stage, archive, archive_kind_for(args.os))
    sidecar = write_sidecar(archive)
    _log(f"sidecar -> {sidecar}")

    verify_archive_checksum(archive)
    problems = check_bundle_members(list_members(archive), args.os)
    if problems:
        raise BundleError(f"assembled archive violates D-layout contract: {problems}")
    if args.skip_pyinstaller:
        note = "fabricated stub" if app_stubbed else "reused staged tree"
        _log(f"smoke skipped (--skip-pyinstaller, {note}): layout-test bundle, NOT release-grade")
    else:
        smoke_app(stage / "app", args.os)
    _log(f"bundle ready: {archive} ({archive.stat().st_size} bytes)")
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build an AIHR turnkey bundle (app + vendored pg + templates)."
    )
    mode = parser.add_argument_group("target selection")
    mode.add_argument("--os", choices=OS_NAMES, help="target OS")
    mode.add_argument("--arch", choices=ARCH_NAMES, default="x86_64", help="target CPU arch")
    mode.add_argument("--version", help="bundle version, e.g. 0.4.0")
    mode.add_argument("--out", type=Path, default=Path("dist"), help="output dir (default: dist/)")
    mode.add_argument("--repo", type=Path, default=default_repo_root(), help="repo root")
    mode.add_argument(
        "--pg-cache",
        type=Path,
        default=default_pg_cache_dir(),
        help="theseus asset cache dir (sha256-checked before reuse)",
    )
    mode.add_argument(
        "--skip-pyinstaller",
        action="store_true",
        help="do not freeze app/: reuse stage/app if present, else fabricate a layout stub "
        "(core-only bundle for selftest; NEVER release-grade)",
    )
    mode.add_argument("--skip-pg", action="store_true", help="reuse staged pg/ tree")
    ops = parser.add_argument_group("archive operations (no build)")
    ops.add_argument("--list", action="store_true", help="print archive members and exit")
    ops.add_argument(
        "--verify", action="store_true", help="verify archive checksum + layout and exit"
    )
    ops.add_argument(
        "--archive", type=Path, help="archive for --list/--verify (default: newest in --out)"
    )
    parser.add_argument(
        "--self-test", action="store_true", help="run pure-logic tests offline and exit"
    )
    args = parser.parse_args(argv)

    if args.self_test:
        return args
    if args.list or args.verify:
        if args.archive is None:
            args.archive = _newest_archive(args.out, args.os, args.arch)
        return args
    if not args.os or not args.version:
        parser.error(
            "--os and --version are required for a build (or use --list/--verify/--self-test)"
        )
    return args


def _newest_archive(out: Path, os_name: str | None, arch: str | None) -> Path:
    pattern = f"aihr-*-{os_name or '*'}-{arch or '*'}.*"
    candidates = sorted(out.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        raise BundleError(f"no archive matching {pattern} in {out}")
    return candidates[0]


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        if args.self_test:
            from scripts.bundle_selftest import run_self_test

            return run_self_test()
        if args.list:
            return handle_list(args.archive)
        if args.verify:
            return handle_verify(args.archive)
        return build_bundle(args)
    except BundleError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"error: subprocess failed ({exc.cmd[0]} exit {exc.returncode})", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
